first calendar
ReiyaPr/ruby-practices pull request #1
Opened 2021-02-03 15:46 UTC by ReiyaPr

2021-02-08 00:20 UTC, kakutani requested changes
「間違い」ではないけれど、Rubyでは別の書き方をすることが多いかなあ、という点をコメントしました。

2021-02-08 00:20 UTC, kakutani commented on 02.calendar/calendar.rb
> +if options["m"] == nil
Rubyでは`nil`と明示的に比較することは冗長なのであまり好まれません。
参考にしてください。
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/NonNilCheck
(日本語で解説している記事もたくさんあると思います)

2021-02-08 00:20 UTC, kakutani commented on 02.calendar/calendar.rb
> +if options["y"] == nil
`nil`の明示的なチェック(取得月と同様)

2021-02-08 00:20 UTC, kakutani commented on 02.calendar/calendar.rb
> +print "\n"
文字列の出力の最後に改行を付けるのであれば `print` よりも `puts` のほうが簡潔です。

2021-02-08 00:20 UTC, kakutani commented on 02.calendar/calendar.rb
> +print "\n"
ここも、文字列の出力の最後に改行を付けるのであれば `print` よりも `puts` のほうが簡潔です。

2021-02-08 00:20 UTC, kakutani commented on 02.calendar/calendar.rb
> +    print day.day.to_s.rjust(2)
`day.day`という変数名が気になりました。「日にちの日にち」とは何だろう? と思いました。
ブロック引数の`day`は、実際には`Date`(日付)のインスタンスが格納されていそうですね。

…そうなると、`days_list`もいまは「日にちのリスト」という名前になっていますが、実際には「日付のリスト」では?

2021-02-08 00:24 UTC, kakutani reviewed
修正が必須というわけではないものや、単なるコメントです。

2021-02-08 00:24 UTC, kakutani commented on 02.calendar/calendar.rb
> +  month = options["m"].to_i
今回の課題の範囲ではないと思いますが、`calendar.rb -m Feb`とした場合にエラーで終了してしまいそうですね。

2021-02-08 00:24 UTC, kakutani commented on 02.calendar/calendar.rb
> +  year = options["y"].to_i
ここも今回の課題の範囲ではないと思いますが、`calendar.rb -y NextYear`とした場合にエラーで終了してしまいそうですね。

2021-02-08 00:24 UTC, kakutani commented on 02.calendar/calendar.rb
> +print "\n"
ここは、カレンダーの最後に「改行を出力したい」という意図だと思うので、`print`でよさそうです(他のコメントで`puts`がいいんじゃないかとコメントしましたが、ここはこれでよさそう)

2021-02-08 00:27 UTC, kakutani commented on 02.calendar/calendar.rb
> +  if day.strftime('%w').to_i == 6
`6` がいわゆるマジックナンバーなので、何を意味するのかを定数などで説明するとよさそうですが、Rubyの`Date`には曜日を判定できるメソッドが用意されているので、それを使ったほうがコードの意図は明確になるかもしれません。
https://rurema.clear-code.com/2.1.0/class/Date.html

2021-02-08 00:28 UTC, kakutani commented on 02.calendar/calendar.rb
> +  if lines_num == 0
`Numeric#zero?` というメソッドもあります 
https://rurema.clear-code.com/2.1.0/method/Numeric/i/zero=3f.html

2021-02-08 12:14 UTC, kakutani requested changes
細かいですが、条件文とコメントの使いかたを指摘しました。

2021-02-08 12:14 UTC, kakutani commented on 02.calendar/calendar.rb
> +if !options["m"]
「もしもオプションにmが設定されていなかったら……"という条件文になっているので、素直に
`if options["m"]`としてみるのはどうでしょう?

2021-02-08 12:14 UTC, kakutani commented on 02.calendar/calendar.rb
> +if !options["y"]
ここも`if not`になっていますね。

2021-02-08 12:14 UTC, kakutani commented on 02.calendar/calendar.rb
> +    #2週目以降の出力処理。日付が土曜日であれば改行
[nits] コメントのインデントがずれているように見えますね(もう2スペース左かな?)

2021-02-08 12:14 UTC, kakutani commented on 02.calendar/calendar.rb
> +# clsss Dateのインポート
[nits] `clsss` とは?
また、「Dateのインポート」は `require "date"`以上に情報は増えていないので、このコメントは削除でよさそう。

2021-02-08 12:14 UTC, kakutani commented on 02.calendar/calendar.rb
> +#option導入の準備
[nits] このコメントも情報は増えていないから不要かな

2021-02-08 12:16 UTC, kakutani commented
上記以外にも、全体的にコード中のコメントについて、コードのやっていること(How)と同じ内容はコメントしないほうがよさそうだな、と思いました。

コードだけを見ても意図が伝わりづらい場合などは、コメントで補足しておくと良いと思いますが、コードのHowと1対1になっているような場合は冗長なだけかな、と思いました。

2021-02-08 12:38 UTC, kakutani commented on 02.calendar/calendar.rb
> +dates_list = [*date_first..date_last]
修正してもらったのにさらに絡んでしまって恐縮ですが、`dates` = 日付が複数 の `list` = 並んでるやつ、というのは冗長な気がしてきました。

これは「月の最初から最後までの日にちのリスト」なんですよね。
`dates_in_month` とかのほうが意図をあらわしているかもしれないなあと思いました。
あるいは、ここではカレンダーなことは自明だから、`target_dates` とかでもいいかもしれません。
(`target`ってなんだよ…という気持ちにもなるので、別のいい名前があれば…)

2021-02-08 12:44 UTC, kakutani commented on 02.calendar/calendar.rb
> +    print date.day.to_s.rjust(2)
土曜日でも、土曜日以外でも、「2桁の文字列としてフォーマットする」部分は同じですね。
となれば、土曜日かどうかで分岐するのは土曜日固有の箇所にすると、この重複をまとめられそうですね。

```
cal_day = ... #日付のフォーマット
if date.saturday?
  puts cal_day
else
  print "#{cal_day} "
end

2021-02-08 12:45 UTC, kakutani commented on 02.calendar/calendar.rb
> +    print date.day.to_s.rjust(2)
土曜日は `print "#{cal_day}\n"` として、土曜と土曜以外での違いをわかりやすくしてもいいかもしれませんね。

2021-02-08 12:46 UTC, kakutani commented
だいぶいい感じになってきました!! …ので、細かいところが目につくようになってしまいました。
せっかくなので、もう少し整えてみるのはどうでしょうか?

2021-02-08 15:17 UTC, ReiyaPr commented
有用なご指摘、本当にありがとうございます！
次からは冗長過ぎず、情報が増えているかどうか考えながらコメントを残したいと思います
変数名の決定は難しいですね....

2021-02-08 23:30 UTC, kakutani commented
かなりスッキリしてきました!!

> 次からは冗長過ぎず、情報が増えているかどうか考えながらコメントを残したいと思います

作業中に自分向けのコメントを残すのは良いプラクティスだと思うので、そこは無理せずとも大丈夫です。
提出物は実務でいえばチームに向けて提出する成果物なので、そこは考えかたを切り替えてもらえるといいなと思います。

「このコードは動いているのにしつこいな…」と思われるかもしれませんが、「次から」といわず今回のでもう少しやってみましょうか。
私からレビュー指摘がついた部分のコメントは削除されましたが、まだいくつかコメントが残っていると思います。
これらはすべて残すべきと判断されましたか?  残しておいてもよさそうなものと、残さなくてもよさそうなものがあると思います。
ぜひ、そういう視点でコード全体を読み直してみてください。

コードを見直すときに、空についても意識してみてください。L22〜L38あたりは、空行が入ったり入ってなかったりする箇所がありますね。日本語でいえば「段落区切り」みたいなものだと考えてみてください。コードの意図としてまとまりのあるものは寄せてみてください(L40〜53はまとまっているから空行がありませんよね?)

意味的なまとまりをつくっていくと、`day_first_num` の置き場所が、ここでいいのかな? という気持ちになりそうです。宣言する場所と、使う場所はあまり遠くないほうがよいでしょう(読み手の短期記憶に負担をかけることになります)。

2021-02-08 23:38 UTC, kakutani commented
...続きです。

> 変数名の決定は難しいですね....

これは難しいですね…。

上のコメントで言及した`day_first_num` もまだ工夫できそうです。
L43で day(日)_first(最初)_num(数)だと、日にちの最初の数とは? と思ったのですが、少し上(離れたところ)のL29で宣言されていました。

`date_first_num = date_first.strftime('%w').to_i`

ということは、これは「月の最初の日々の曜日を、日曜日を0起点とした数字で表現したもの」ですね。…とこのコメントを書いていて、この右辺は:

`date_first.wday`

と書けることに気づきました。[instance method Date\#wday \(Ruby 3\.0\.0\)](https://rurema.clear-code.com/3.0.0/method/Date/i/wday.html)

…となると、

`date_first_num = date_first.wday`

という式は、そんなに情報が増えなさそうです(文字数も変わらない)。
そして、この値は、月初の曜日に合わせて空白を調整するだけなので、このプログラム全体では1回しか実行されません。
となると、L42あたりは:

```ruby
if lines_num.zero?
  print "   " * date_first.wday
  ...
```

で十分かもしれません(wdayが曜日をあらわす数値である、というのはプログラマー相手なら前提にして構わない名前だと思います)。

2021-02-08 23:43 UTC, kakutani commented on 02.calendar/calendar.rb
> +
この空行は不要ですね

2021-02-09 10:21 UTC, ReiyaPr commented
処理の段落？をイメージして、余分な空行を削除しました。
変数名に対するコメントは、変数名・フォーマットで明示できると考え削除しました。
wdayメソッドを利用して、処理を短縮しました。
確認お願いします！

2021-02-09 11:56 UTC, kakutani commented on 02.calendar/calendar.rb
> +print "\n"
…お、惜しい!
ファイルの最後には、改行を入れてください!
https://docs.komagata.org/5460

2021-02-09 11:56 UTC, kakutani approved these changes

2021-02-09 12:00 UTC, kakutani commented
おつかれさまでした! 課題としてはオッケーです!

2021-02-27 10:58 UTC, merged